version: '3'

services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    links:
      - database
    volumes:
      - /usr/app/node_modules
      - ../../:/usr/app
    ports:
      - '4000:4000'
    env_file:
      - ../../.env
    environment:
      PORT: 4000
      DATABASE_URL: postgres://postgres:postgres@database/reachout
    entrypoint:
      - /usr/app/docker/dev/entrypoint.sh
    command:
      - yarn
      - start
    depends_on:
      - "database"
  database:
    image: postgres:9.6-alpine
    expose:
      - '5432'
    ports:
      - '5433:5432'
    volumes:
      - reachout_data:/var/lib/data/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reachout
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5


volumes:
  reachout_data:
    external: true
